version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; ./api/manage.py migrate;service nginx restart; ./api/manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_CONFIGURATION: Production
      DJANGO_SECRET_KEY: "БартоломеоДиаш"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db